### ISSUE TITLE
Missing Javadoc when building

### ISSUE THREAD

**Issue by marcomicera** [QMSTR/qmstr#536]
**Describe the bug**
Lots of Maven repositories need Javadoc, for instance:
- [github.com/rubenlagus/TelegramBots](https://github.com/rubenlagus/TelegramBots)
- [github.com/kingston-csj/jforgame](https://github.com/kingston-csj/jforgame)
- [github.com/Ardesco/Selenium-Maven-Template](https://github.com/Ardesco/Selenium-Maven-Template)

**To Reproduce**
1. Move to the [`deploy` folder](https://github.com/endocode/qmstr/tree/feature/self-contained-modules/deploy):
    ```bash
    cd deploy
    ```
1. Deploy our DGraph StatefulSet:
    ```bash
    kubectl apply -k dgraph
    ``` 
1. Explicitly specify all Docker image tags to enable manual deployment in [`deploy/qmstr/kustomization.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/kustomization.yaml):
    ```yaml
    # In case of manual deployment, insert the desired image tags here.
    images:
      - name: endocodeci/qmstr-master
        newTag: sha-1068725
      - name: endocodeci/qmstr-client-mvn
        newTag: sha-1068725
      - name: endocodeci/pom-patch
        newTag: sha-1068725
    ```
1. Override the repository URL in [`deploy/qmstr/repo-url.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/repo-url.yaml).\
The patch will be automatically applied by Kustomize.
1. Deploy QMSTR:
    ```bash
    kubectl apply -k qmstr
    ```

**Expected behavior**
The build phase shouldn't fail because of missing Javadoc.
