### ISSUE TITLE
QMSTR Maven plugin: "qmstr" no package found

### ISSUE THREAD

**Issue by marcomicera** [QMSTR/qmstr#537]
**Describe the bug**
Upon building [github.com/fanchaoo/hahu](https://github.com/fanchaoo/hahu), the client container fails with the following:

```
[INFO] BUILD FAILURE
[ERROR] Failed to execute goal org.qmstr:qmstr-maven-plugin:0.5:qmstr (qmstrpackage) on project hahu: qmstr: no package found -> [Help 1]
```

[Patched `pom.xml` file](https://github.com/QMSTR/qmstr/files/5339010/pom.xml.txt).

**To Reproduce**
1. Move to the [`deploy` folder](https://github.com/endocode/qmstr/tree/feature/self-contained-modules/deploy):
    ```bash
    cd deploy
    ```
1. Deploy our DGraph StatefulSet:
    ```bash
    kubectl apply -k dgraph
    ``` 
1. Explicitly specify all Docker image tags to enable manual deployment in [`deploy/qmstr/kustomization.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/kustomization.yaml):
    ```yaml
    # In case of manual deployment, insert the desired image tags here.
    images:
      - name: endocodeci/qmstr-master
        newTag: sha-1068725
      - name: endocodeci/qmstr-client-mvn
        newTag: sha-1068725
      - name: endocodeci/pom-patch
        newTag: sha-1068725
    ```
1. Override the repository URL in [`deploy/qmstr/repo-url.yaml`](https://github.com/endocode/qmstr/blob/feature/self-contained-modules/deploy/qmstr/repo-url.yaml).\
The patch will be automatically applied by Kustomize.
1. Deploy QMSTR:
    ```bash
    kubectl apply -k qmstr
    ```
